language: php

php:
  - 5.3
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

install:
  - composer install --prefer-source --no-interaction
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
script:
  - ./phpunit.phar --coverage-text

