language: php

php:
  - 5.3
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

install:
  - composer install --prefer-source --no-interaction
  - phpunit --version
script:
  - phpunit --coverage-text

