language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - hhvm

matrix:
  allow_failures:
    - php: 7.4snapshot

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text

